api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from . import views

urlpatterns = [
    path('login/', TokenObtainPairView.as_view(), name='login'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('register/', views.registerUserView, name='register'),
    path('todo/', views.todoView.as_view(), name='todo'),
    path('make-done/', views.makeTodoDone, name='make-done'),
]

mvt/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("register",  views.registerView, name="register"),
    path("login",  views.loginView, name="login"),
    path("logout",  views.logoutView, name="logout"),
    path("delete", views.deleteTodoView, name="delete_todo"),
    path("done", views.markTodoDoneView, name="done"),
    path("todolog", views.todoLogView, name="todolog"),
    path("update-todo/", views.todoUpdateView, name="update"),
    path("profilepage", views.profileView, name="profilepage"),
    path("", views.homeView, name="home"),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("api.urls")),
    path("", include("mvt.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mvt/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone


class User(AbstractUser):
    first_name = None
    last_name = None



class Todo(models.Model):
    title = models.CharField(max_length=40)
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    expire = models.DateTimeField()
    user = models.ForeignKey(User, related_name="todos", on_delete=models.CASCADE)

    @property
    def is_expired(self):
        return self.expire < timezone.now()

    class Meta:
        ordering = ['-expire']

mvt/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import User, Todo
from django import forms
from django.forms.widgets import TextInput, PasswordInput
from django.utils import timezone


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Enter username'}),
            'email': forms.EmailInput(attrs={'placeholder': 'eg: name@gmail.com'}),
            'password1': forms.PasswordInput(attrs={'placeholder': 'password'}),
            'password2': forms.PasswordInput(attrs={'placeholder': 'enter same password'}),
        }


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(attrs={'placeholder': "Enter username"}))
    password = forms.CharField(widget=PasswordInput(attrs={'placeholder': "Enter password"}))


class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'expire']

        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Enter title'}),
            'expire': forms.DateInput(attrs={'placeholder': 'YYYY-MM-DD HH:MM'}),
        }
    
    

mvt/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import forms, models
from django.contrib.auth import authenticate, login, logout
from django.utils import timezone
from django.db.models import F

def homeView(request):
    user = request.user
    if not user.is_authenticated:
        return redirect("login")
    form = forms.TodoForm()
    if request.method == "POST":
        form = forms.TodoForm(data=request.POST)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.user = user
            todo.save()
            return redirect("home")
    todos = user.todos.filter(completed=False)
    context = {"todos": todos, "form": form}
    return render(request, 'mvt/index.html', context=context)



def registerView(request):
    form = forms.CreateUserForm()

    if request.method == "POST":
        form = forms.CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            if user is not None:
                login(request=request, user=user)
                return redirect("home")
    context = {'register_form': form}
    return render(request, 'mvt/register.html', context=context)


def loginView(request):
    form = forms.LoginForm()

    if request.method == "POST":
        form = forms.LoginForm(request, data=request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request=request, user=user)
                return redirect("home")
    
    context = {'login_form': form}

    return render(request, "mvt/login.html", context=context)

def logoutView(request):
    logout(request)
    return redirect('login')

def deleteTodoView(request):
    if request.method == "POST":
        todo_id = request.POST.get("todo_id")
        todo = models.Todo.objects.get(id=todo_id)
        todo.delete()
        return redirect("home")
    return redirect("home")


def markTodoDoneView(request):
    if request.method == "POST":
        todo_id = request.POST.get("todo_id")
        todo = models.Todo.objects.get(id=todo_id)
        todo.completed = True
        todo.completed_at = timezone.now()
        todo.save()
        return redirect("home")
    return redirect("home")

def todoLogView(request):
    user = request.user
    if not user.is_authenticated:
        return redirect("login")
    todos = user.todos.filter(completed=True)
    context = {'todos': todos}
    return render(request, 'mvt/todolog.html', context=context)

def todoUpdateView(request):
    if request.method == "POST":
        todo_id = request.POST.get("todo_id")
        todo = get_object_or_404(models.Todo, pk=todo_id)
        form = forms.TodoForm(data=request.POST, instance=todo)
        if form.is_valid():
            form.save()
            return redirect("home")
    todo_id = request.GET.get("id", None)
    if todo_id is None:
        return redirect("home")
    
    todo = models.Todo.objects.get(id=todo_id)
    if todo.user != request.user:
        return redirect("home")
    
    context = {"todo": todo, "expire": str(todo.expire.astimezone()).split("+")[0]}


    return render(request, 'mvt/updateTodo.html', context=context)



def profileView(request):
    user = request.user
    if not user.is_authenticated:
        return redirect("login")
    todos = user.todos.all()
    total_todo = todos.count()
    completed_todo = todos.filter(completed=True).count()
    expired_todo = todos.filter(expire__lt=timezone.now()).count()
    pending_todo = todos.filter(completed=False, expire__gt=timezone.now()).count()
    context = {"total": total_todo, "user": user, "completed": completed_todo, "expired": expired_todo, "pending": pending_todo}
    return render(request, 'mvt/profile.html', context=context)

mvt/templates/mvt/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>TODO APP</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href={% static 'style.css' %} />
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body class="bg-slate-50">
    {% include 'mvt/navbar.html' %}
    <h1 class="text-center font-bold text-3xl mt-10 mb-14">TODO</h1>
    <div class="flex justify-center w-full flex-col gap-6 items-center">
      {% if not todos %} <p>Nothing here</p> {% endif %}
      {% for todo in todos %}
       {% include 'mvt/todo.html' with context_variable=todo %}
      {% endfor %}
    </div>
    <div class="flex justify-center mt-10">
      <button class="px-4 py-2 bg-green-400 rounded-xl font-medium text-sm hover:bg-green-500 hover:scale-105" id="add-todo">ADD TODO</button>
    </div>
    <div class="absolute top-0 left-0 w-full h-screen justify-center items-center hidden" id="add-todo-modal">
      <div class="bg-black absolute w-full h-screen opacity-30"></div>
      <form method="POST" class="p-10 relative bg-slate-200 rounded-lg flex flex-col gap-5 w-full max-w-[600px]">
        <h1 class="font-semibold text-center text-xl">NEW TODO</h1>
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="bg-green-400 py-1 rounded-lg font-medium hover:bg-green-500">SUBMIT</button>
        <button class="bg-red-400 py-1 rounded-lg font-medium hover:bg-red-500" type="button" id="form-cancle">CANCLE</button>
      </form>
    </div>
  </body>
  <script src={% static 'index.js' %}></script>
</html>

mvt/templates/mvt/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TODO APP | LOGIN</title>
    <link rel="stylesheet" href={% static 'style.css' %} />
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body class="flex justify-center items-center min-h-screen bg-slate-50">
    <form method="POST" class="bg-slate-200 p-10 flex flex-col gap-5 rounded-xl w-full max-w-[600px]" id="add-todo-modal">
      <p class="text-center font-semibold text-xl">WELCOME BACK</p>
      {% csrf_token %} {{ login_form.as_p }}
      <button type="submit" class="w-full bg-green-400 hover:bg-green-500 font-medium py-1 rounded-lg">LOGIN</button>
      <a href="register" class="text-sm text-blue-600 text-center cursor-pointer hover:underline">New here? Register</a>
    </form>
  </body>
</html>

mvt/templates/mvt/navbar.html
<nav class="h-[60px] flex items-center justify-between px-10 bg-slate-200">
    <p>TODO APP</p>
    <ul class="flex gap-5 text-sm underline cursor-pointer">
      <li class="hover:scale-105"><a href="/">Home</a></li>
      <li class="hover:scale-105"><a href="/profilepage">Profile</a></li>
      <li class="hover:scale-105"><a href="/todolog">Todo log</a></li>
    </ul>
    <a href="logout">
      <button class="px-4 py-1 rounded-md bg-black text-white hover:scale-105">Logout</button>
    </a>
  </nav>

mvt/templates/mvt/profile.html
{% comment %} {% load static %} {% endcomment %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>TODO APP</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% comment %} <link rel="stylesheet" href={% static 'style.css' %} /> {% endcomment %}
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body class="bg-slate-50">
    {% include 'mvt/navbar.html' %}
    <main class="min-h-screen pt-10">
        <h1 class="text-center font-medium text-3xl">Welcome {{user.username}}</h1>
        <div class="bg-slate-200 rounded-lg p-10 max-w-[600px] mx-auto mt-5">
            <p class="font-semibold text-xl">Dashboard</p>
            <p>created: {{total}}</p>
            <p>completed: {{completed}}</p>
            <p>expired: {{expired}}</p>
            <p>pending: {{pending}}</p>
        </div>
    </main>
  </body>
  {% comment %} <script src={% static 'index.js' %}></script> {% endcomment %}
</html>

mvt/templates/mvt/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TODO APP | REGISTER</title>
    <link rel="stylesheet" href={% static 'style.css' %} />
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body class="flex justify-center items-center min-h-screen bg-slate-50">
    <form method="POST" autocomplete="off" id="register" class="bg-slate-200 px-10 py-3 flex flex-col gap-4 rounded-xl w-full max-w-[600px]">
      <p class="text-center font-semibold text-xl">CREATE NEW ACCOUNT</p>
      {% csrf_token %} {{register_form.as_p}}
      <button type="submit" value="Register" class="w-full bg-green-400 hover:bg-green-500 font-medium py-1 rounded-lg">REGISTER</button>
      <a href="login" class="text-sm text-blue-600 text-center cursor-pointer hover:underline">Already have an acoount? Login</a>
    </form>
  </body>
</html>

mvt/templates/mvt/todo.html
<label for={{todo.id}} class="min-w-[400px] w-full max-w-[600px]">
<div class="flex justify-between items-center bg-slate-100 px-5 py-2 rounded-xl hover:bg-slate-200 shadow-md">
        <p class="font-semibold">{{ todo.title }}</p>
        {% if todo.is_expired %}<p class="px-1 bg-orange-200 rounded-lg text-sm font-thin"> expired </p>{% endif %}
        <div class="flex gap-2">
            <a href="update-todo/?id={{todo.id}}">
                <button class="rounded-md text-sm bg-yellow-200 px-2 py-2 hover:bg-yellow-300">Update</button>
            </a>
            <form method="POST" action="{% url 'delete_todo' %}">
                {% csrf_token %}
                <input type="hidden" name="todo_id" value="{{ todo.id }}">
                <button type="submit" class="rounded-md text-sm bg-red-200 px-2 py-2 hover:bg-red-300 delete-todo">Delete</button>
            </form>
            <form method="POST" action="{% url 'done' %}">
                {% csrf_token %}
                <input type="hidden" name="todo_id" value="{{ todo.id }}">
                <button class="rounded-md text-sm bg-green-200 px-2 py-2 hover:bg-green-300">Done</button>
            </form>
        </div>
    </div>
</label>

mvt/templates/mvt/todolog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO LOG</title>
    <link rel="stylesheet" href={% static 'style.css' %} />
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    {% include 'mvt/navbar.html' %}
    <main class="max-h-screen flex justify-center pt-10">
        <div class="max-w-[600px] p-10 rounded-lg bg-slate-200 w-full">
            <p class="text-center font-semibold text-xl mb-4">Todo Log</p>
            <div class="flex flex-col gap-4">
                {% for todo in todos %}
                <div class="flex justify-between bg-slate-300 items-center py-2 px-4 rounded-md">
                    <div>
                        <p>{{todo.title}}</p>
                        <p class="text-[10px]">created at: {{todo.created_at}} </p>
                        <p class="text-[10px]">completed at: {{todo.completed_at}} </p>
                        <p class="text-[10px]">was expired: {{todo.is_expired}} </p>
                    </div>
                    <form method="POST" action="{% url 'delete_todo' %}">
                        {% csrf_token %}
                        <input type="hidden" name="todo_id" value="{{ todo.id }}">
                        <button type="submit" class="rounded-md text-sm bg-red-200 px-2 py-2 hover:bg-red-300 delete-todo">Delete</button>
                    </form>
                </div>
                {% endfor %}
            </div>
        </div>
    </main>
</body>
</html>

mvt/templates/mvt/updateTodo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO UPDATE</title>
    <link rel="stylesheet" href={% static 'style.css' %} />
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-50">
    {% include 'mvt/navbar.html' %}
    <main class="max-h-screen flex justify-center pt-10">
        <form method="POST" id="add-todo-modal" class="bg-slate-200 p-10 w-full max-w-[600px] rounded-lg">
            <p class="text-center font-semibold text-xl mb-5">Update Todo</p>
            {% csrf_token %}
            <p class="mb-5">
                <label for="">Title:</label>
                <input type="text" id="id_title" name="title" value="{{todo.title}}">
            </p>
            <p class="mb-10">
                <label for="">Expire:</label>
                <input type="text" id="id_expire" name="expire" value="{{expire}}">
            </p>
            <input type="hidden" name="todo_id" value="{{todo.id}}">
            <button type="submit" class="rounded bg-green-400 px-3 py-1 text-white font-semibold hover:bg-green-600 w-full">UPDATE</button>
        </form>
    </main>
</body>
</html>